version: '3.9'

x-staking-api-build: &staking_api_build
  context: .
  dockerfile: apps/staking-api/Dockerfile

services:
  staking-api:
    build: *staking_api_build
    env_file:
      - apps/staking-api/.env
    ports:
      - "8787:8787"
    restart: unless-stopped

  staking-worker:
    build: *staking_api_build
    env_file:
      - apps/staking-api/.env
    command: ["run", "apps/staking-api/dist/worker.js"]
    restart: unless-stopped
    depends_on:
      - staking-api

